# English Premier League

![Image](tile-premier-league-mar.jpg)

The Premier League is the highest level of the English football league system. Contested by 20 clubs, it operates on a system of promotion and relegation with the English Football League (EFL). Seasons typically run from August to May with each team playing 38 matches against all other teams both home and away. Most games are played on Saturday and Sunday afternoons, with occasional weekday evening fixtures.

We are going to attend to retrieve data of the latest EPL season using Webscraping and feed our data into a Machine Learning Model to predict the matches of each Team . The Packages which will be used to scrape data of the internet is called **Beautiful Soup** . Beautiful Soup is a Python library that is used for web scraping and parsing HTML or XML documents. It provides a convenient way to extract data from web pages by traversing the HTML or XML structure and locating specific elements or attributes.

After Web Scraping and recieve the data , The next step is to feed our a data into a Machine Learning Algorithm

# Import Packages/Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score

# Import The Data

In [2]:
match_data = pd.read_csv('matches.csv', index_col=0)

In [3]:
match_data

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,Tottenham,...,Match Report,NaN,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,Norwich City,...,Match Report,NaN,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,Arsenal,...,Match Report,NaN,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,...,Match Report,NaN,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,...,Match Report,NaN,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2021-05-02,19:15,Premier League,Matchweek 34,Sun,Away,L,0.0,4.0,Tottenham,...,Match Report,NaN,8.0,1.0,17.4,0.0,0.0,0.0,2021,Sheffield United
39,2021-05-08,15:00,Premier League,Matchweek 35,Sat,Home,L,0.0,2.0,Crystal Palace,...,Match Report,NaN,7.0,0.0,11.4,1.0,0.0,0.0,2021,Sheffield United
40,2021-05-16,19:00,Premier League,Matchweek 36,Sun,Away,W,1.0,0.0,Everton,...,Match Report,NaN,10.0,3.0,17.0,0.0,0.0,0.0,2021,Sheffield United
41,2021-05-19,18:00,Premier League,Matchweek 37,Wed,Away,L,0.0,1.0,Newcastle Utd,...,Match Report,NaN,11.0,1.0,16.0,1.0,0.0,0.0,2021,Sheffield United
42,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,1.0,0.0,Burnley,...,Match Report,NaN,12.0,3.0,17.0,0.0,0.0,0.0,2021,Sheffield United

In [4]:
match_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1389 entries, 1 to 42
Data columns (total 27 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1389 non-null   object
 1   time          1389 non-null   object
 2   comp          1389 non-null   object
 3   round         1389 non-null   object
 4   day           1389 non-null   object
 5   venue         1389 non-null   object
 6   result        1389 non-null   object
 7   gf            1389 non-null   float64
 8   ga            1389 non-null   float64
 9   opponent      1389 non-null   object
 10  xg            1389 non-null   float64
 11  xga           1389 non-null   float64
 12  poss          1389 non-null   float64
 13  attendance    693 non-null    float64
 14  captain       1389 non-null   object
 15  formation     1389 non-null   object
 16  referee       1389 non-null   object
 17  match report  1389 non-null   object
 18  notes         0 non-null      float64
 19  sh            1389 non-null   float64
 20  sot           1389 non-null   float64
 21  dist          1388 non-null   float64
 22  fk            1389 non-null   float64
 23  pk            1389 non-null   float64
 24  pkatt         1389 non-null   float64
 25  season        1389 non-null   int64
 26  team          1389 non-null   object
dtypes: float64(13), int64(1), object(13)
memory usage: 303.8+ KB

## Cleaning Our Data

In [5]:
#remove uneccessary columns 
match_data.drop(['attendance','captain','formation','referee','match report','notes'],axis=1)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,xga,poss,sh,sot,dist,fk,pk,pkatt,season,team
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,Tottenham,...,1.3,64.0,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,Norwich City,...,0.1,67.0,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,Arsenal,...,0.1,80.0,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,...,0.8,61.0,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,...,0.4,63.0,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2021-05-02,19:15,Premier League,Matchweek 34,Sun,Away,L,0.0,4.0,Tottenham,...,2.0,34.0,8.0,1.0,17.4,0.0,0.0,0.0,2021,Sheffield United
39,2021-05-08,15:00,Premier League,Matchweek 35,Sat,Home,L,0.0,2.0,Crystal Palace,...,2.1,50.0,7.0,0.0,11.4,1.0,0.0,0.0,2021,Sheffield United
40,2021-05-16,19:00,Premier League,Matchweek 36,Sun,Away,W,1.0,0.0,Everton,...,1.3,38.0,10.0,3.0,17.0,0.0,0.0,0.0,2021,Sheffield United
41,2021-05-19,18:00,Premier League,Matchweek 37,Wed,Away,L,0.0,1.0,Newcastle Utd,...,1.5,50.0,11.0,1.0,16.0,1.0,0.0,0.0,2021,Sheffield United
42,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,1.0,0.0,Burnley,...,1.0,41.0,12.0,3.0,17.0,0.0,0.0,0.0,2021,Sheffield United

In [6]:
# convert date column into date/time Dtype
match_data['date'] = pd.to_datetime(match_data['date'])

## Creating Numerical Predictors for Machine Learning

In [7]:
#Convert Features to Numerical data type
match_data['venue_code'] = match_data['venue'].astype("category").cat.codes
match_data['opponent_code'] = match_data['opponent'].astype("category").cat.codes
match_data['day_code'] = match_data['date'].dt.dayofweek
match_data['hour'] = match_data['time'].str.replace(":.+","",regex=True).astype("int")
match_data['target'] = (match_data['result'] == 'W').astype("int")

## Create a Machine Learning Model

In [8]:
rf = RandomForestClassifier(n_estimators=50,min_samples_split=10,random_state=1)

In [9]:
train = match_data[match_data['date'] < '2022-01-01']

In [10]:
test = match_data[match_data['date'] > '2022-01-01']

In [11]:
X = ["venue_code",'opponent_code','hour','day_code']

In [12]:
rf.fit(train[X],train['target'])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [13]:
predictions = rf.predict(test[X])

In [14]:
accuracy = accuracy_score(test['target'],predictions)

In [15]:
accuracy

0.6123188405797102

In [16]:
newDataFrame = pd.DataFrame(dict(actual=test['target'],prediction=predictions))

In [17]:
pd.crosstab(index=newDataFrame['actual'],columns=newDataFrame['prediction'])

prediction    0   1
actual
0           141  31
1            76  28

In [18]:
precision_score(test['target'],predictions)

0.4745762711864407

## Improving our Model Prediction precision

In [19]:
grouped_match_data = match_data.groupby("team")

In [20]:
group = grouped_match_data.get_group("Manchester United").sort_values("date")

In [21]:
def rolling_averages(group,cols,new_cols):
    group = group.sort_values('date')
    rolling_stats = group[cols].rolling(3,closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

cols = ['gf','ga','sh','sot','dist','fk','pk','pkatt']
new_cols = [f"{c}_rolling" for c in cols]

In [22]:
rolling_averages(group,cols,new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,hour,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
5,2020-10-17,20:00,Premier League,Matchweek 5,Sat,Away,W,4.0,1.0,Newcastle Utd,...,20,1,1.666667,3.666667,9.000000,2.333333,19.800000,0.333333,0.666667,0.666667
7,2020-10-24,17:30,Premier League,Matchweek 6,Sat,Home,D,0.0,0.0,Chelsea,...,17,0,2.666667,3.000000,12.333333,4.666667,20.000000,0.000000,0.666667,1.000000
9,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Home,L,0.0,1.0,Arsenal,...,16,0,1.666667,2.333333,15.000000,5.333333,19.700000,0.000000,0.333333,0.666667
11,2020-11-07,12:30,Premier League,Matchweek 8,Sat,Away,W,3.0,1.0,Everton,...,12,1,1.333333,0.666667,16.666667,5.666667,18.300000,0.000000,0.000000,0.333333
12,2020-11-21,20:00,Premier League,Matchweek 9,Sat,Home,W,1.0,0.0,West Brom,...,20,1,1.000000,0.666667,12.000000,3.666667,18.733333,0.666667,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40,2022-04-02,17:30,Premier League,Matchweek 31,Sat,Home,D,1.0,1.0,Leicester City,...,17,0,1.333333,2.000000,12.666667,3.666667,15.333333,0.333333,0.000000,0.000000
41,2022-04-09,12:30,Premier League,Matchweek 32,Sat,Away,L,0.0,1.0,Everton,...,12,0,1.666667,2.333333,9.000000,4.333333,14.333333,0.000000,0.000000,0.000000
42,2022-04-16,15:00,Premier League,Matchweek 33,Sat,Home,W,3.0,2.0,Norwich City,...,15,1,1.333333,1.333333,11.333333,5.000000,15.333333,0.000000,0.000000,0.000000
43,2022-04-19,20:00,Premier League,Matchweek 30,Tue,Away,L,0.0,4.0,Liverpool,...,20,0,1.333333,1.333333,14.333333,6.000000,15.666667,0.333333,0.000000,0.000000
44,2022-04-23,12:30,Premier League,Matchweek 34,Sat,Away,L,1.0,3.0,Arsenal,...,12,0,1.000000,2.333333,11.333333,4.666667,17.800000,0.333333,0.000000,0.000000

In [23]:
matches_rolling = match_data.groupby("team").apply(lambda x: rolling_averages(x,cols,new_cols))

In [24]:
matches_rolling

                                 date   time            comp         round  \
team
Arsenal                 6  2020-10-04  14:00  Premier League   Matchweek 4
                        7  2020-10-17  17:30  Premier League   Matchweek 5
                        9  2020-10-25  19:15  Premier League   Matchweek 6
                        11 2020-11-01  16:30  Premier League   Matchweek 7
                        13 2020-11-08  19:15  Premier League   Matchweek 8
...                               ...    ...             ...           ...
Wolverhampton Wanderers 32 2022-03-13  14:00  Premier League  Matchweek 29
                        33 2022-03-18  20:00  Premier League  Matchweek 30
                        34 2022-04-02  15:00  Premier League  Matchweek 31
                        35 2022-04-08  20:00  Premier League  Matchweek 32
                        36 2022-04-24  14:00  Premier League  Matchweek 34

                            day venue result   gf   ga         opponent  ...  \
team                                                                     ...
Arsenal                 6   Sun  Home      W  2.0  1.0    Sheffield Utd  ...
                        7   Sat  Away      L  0.0  1.0  Manchester City  ...
                        9   Sun  Home      L  0.0  1.0   Leicester City  ...
                        11  Sun  Away      W  1.0  0.0   Manchester Utd  ...
                        13  Sun  Home      L  0.0  3.0      Aston Villa  ...
...                         ...   ...    ...  ...  ...              ...  ...
Wolverhampton Wanderers 32  Sun  Away      W  1.0  0.0          Everton  ...
                        33  Fri  Home      L  2.0  3.0     Leeds United  ...
                        34  Sat  Home      W  2.0  1.0      Aston Villa  ...
                        35  Fri  Away      L  0.0  1.0    Newcastle Utd  ...
                        36  Sun  Away      L  0.0  1.0          Burnley  ...

                            hour  target  gf_rolling  ga_rolling sh_rolling  \
team
Arsenal                 6     14       1    2.000000    1.333333   7.666667
                        7     17       0    1.666667    1.666667   5.333333
                        9     19       0    1.000000    1.666667   7.000000
                        11    16       1    0.666667    1.000000   9.666667
                        13    19       0    0.333333    0.666667   9.666667
...                          ...     ...         ...         ...        ...
Wolverhampton Wanderers 32    14       1    1.333333    1.000000  12.333333
                        33    20       0    1.666667    0.666667  12.333333
                        34    15       1    2.333333    1.000000  13.000000
                        35    20       0    1.666667    1.333333  13.000000
                        36    14       0    1.333333    1.666667  10.000000

                           sot_rolling dist_rolling fk_rolling  pk_rolling  \
team
Arsenal                 6     3.666667    14.733333   0.666667    0.000000
                        7     3.666667    15.766667   0.000000    0.000000
                        9     3.666667    16.733333   0.666667    0.000000
                        11    4.000000    16.033333   1.000000    0.000000
                        13    2.666667    18.033333   1.000000    0.333333
...                                ...          ...        ...         ...
Wolverhampton Wanderers 32    3.666667    19.300000   0.000000    0.000000
                        33    4.333333    19.600000   0.000000    0.000000
                        34    5.333333    19.833333   0.000000    0.000000
                        35    5.000000    18.533333   0.000000    0.000000
                        36    4.666667    17.633333   0.000000    0.000000

                            pkatt_rolling
team
Arsenal                 6        0.000000
                        7        0.000000
                        9        0.000000
                        11       0.000000
                        13       0.333333
...                                   ...
Wolverhampton Wanderers 32       0.000000
                        33       0.000000
                        34       0.000000
                        35       0.000000
                        36       0.000000

[1317 rows x 40 columns]

In [25]:
matches_rolling = matches_rolling.droplevel('team')

In [26]:
matches_rolling.index = range(matches_rolling.shape[0])

In [27]:
def make_predictions(data,predictors):
    train = data[data['date'] < '2022-01-01']
    test = data[data['date'] > '2022-01-01']
    rf.fit(train[predictors],train['target'])
    predictions = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test['target'],predicted=predictions),index=test.index)
    precision = precision_score(test['target'],predictions)
    return combined , precision

In [28]:
match_predictions , precision = make_predictions(matches_rolling, X + new_cols)

In [29]:
match_predictions = match_predictions.merge(matches_rolling[['team','opponent','result','date']],left_index=True,right_index=True)

In [30]:
match_predictions

,actual,predicted,team,opponent,result,date
55,0,0,Arsenal,Burnley,D,2022-01-23
56,1,0,Arsenal,Wolves,W,2022-02-10
57,1,0,Arsenal,Brentford,W,2022-02-19
58,1,1,Arsenal,Wolves,W,2022-02-24
59,1,1,Arsenal,Watford,W,2022-03-06
...,...,...,...,...,...,...
1312,1,0,Wolverhampton Wanderers,Everton,W,2022-03-13
1313,0,0,Wolverhampton Wanderers,Leeds United,L,2022-03-18
1314,1,0,Wolverhampton Wanderers,Aston Villa,W,2022-04-02
1315,0,0,Wolverhampton Wanderers,Newcastle Utd,L,2022-04-08
1316,0,0,Wolverhampton Wanderers,Burnley,L,2022-04-24

In [31]:
precision

0.625